---
title: "Airbnb Nashville"
---

```{r}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(stringr)
library(ggcorrplot)
```

```{r}
listings <- read_csv("~/Documents/MSDS/MSDS_2019_Fall/Survey_DS_Applications/Group Work/Group Project/data/listings.csv")
```



Filtering Data
```{r}
listings <- listings %>% 
  filter(smart_location == "Nashville, TN",
         bed_type == "Real Bed"
         )
```


```{r}
listings %>% 
  group_by(last_scraped) %>% 
  summarize(count = n())

listings <- listings %>% 
  mutate(price = as.numeric(str_sub(price, 2)))


listings <- listings %>% 
  mutate(neighborhood_num = str_sub(neighbourhood_cleansed, 9, str_length(neighbourhood_cleansed)))

listings2 <- listings2 %>% 
  mutate(neighborhood_num = str_sub(neighborhood_num,2,str_length(neighborhood_num)))

```


```{r}
listings %>% 
  filter(!is.na(review_scores_rating)) %>% 
  group_by(host_is_superhost) %>%
  summarize(count = n(),
    rating_avg = mean(review_scores_rating/20, na.rm=TRUE),
    rating_median = median(review_scores_rating/20, na.rm=TRUE),
    rating_var = var(review_scores_rating/20, na.rm=TRUE),
    beds_avg = mean(beds, na.rm=TRUE),
    bedrooms_avg = mean(bedrooms),
    accom_avg = mean(accommodates),
    price_avg = mean(price,  na.rm=TRUE),
    price_median = median(price,na.rm=TRUE)
)

listings2 %>% 
  filter(!is.na(review_scores_rating) & neighborhood_num == " 19") %>% 
  group_by(host_is_superhost) %>%
  summarize(count = n(),
    rating_avg = mean(review_scores_rating/20, na.rm=TRUE),
    rating_median = median(review_scores_rating/20, na.rm=TRUE),
    rating_var = var(review_scores_rating/20, na.rm=TRUE),
    beds_avg = mean(beds, na.rm=TRUE),
    bedrooms_avg = mean(bedrooms),
    accom_avg = mean(accommodates),
    price_avg = mean(price,  na.rm=TRUE),
    price_median = median(price,na.rm=TRUE)
)


listings2 %>% 
  filter(neighborhood_num == " 19" & !is.na(review_scores_rating)) %>%
  group_by(host_is_superhost) %>%
  summarize(count = n())
  


```


```{r}
mean(listings$review_scores_rating/20, na.rm=-TRUE)
# 2 bedrooms
#3 beds
# Accomodates 6


listings %>% 
  group_by(room_type) %>% 
  summarize(count = n())

```


```{r}
airbnb_corr_subset <- listings %>% 
  select(accommodates, bedrooms, beds, price, host_is_superhost, room_type, number_of_reviews, review_scores_rating, neighborhood_num, bathrooms, longitude, latitude) %>% 
  mutate(lat_test = latitude + longitude)

airbnb_corr_subset$neighborhood_num <- as.numeric(airbnb_corr_subset$neighborhood_num)

airbnb_corr_subset <- airbnb_corr_subset %>% 
  mutate(host_is_superhost = ifelse(host_is_superhost == TRUE, 1, 0),
         room_type = case_when(
          room_type == "Entire home/apt" ~ 3,
          room_type == "Private room" ~ 2,
          room_type == "Shared room" ~ 1,
          room_type == "Hotel room" ~ 4)
         )

airbnb_corr_subset <- na.omit(airbnb_corr_subset)
corr_matrix <- cor(airbnb_corr_subset)


listings %>% 
  group_by(room_type) %>% 
  summarize(count = n(),
            avg_price = mean(price, na.rm=TRUE))

ggcorrplot(corr_matrix,
           hc.order=TRUE,
          method = "circle",
           type="lower",
           lab=TRUE,
           lab_size = 2.5,
           col=c("tomato", "white", "springgreen3")) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"),
        axis.text.x = element_text(angle = 50, hjust = 1, vjust=1))

```



```{r}
listings$accommodates <- as.numeric(listings$accommodates)

sum(is.na(listings$review_scores_rating))


listings %>% 
  filter(accommodates <= 10) %>% 
  ggplot(aes(x=accommodates, y=price, group=accommodates)) +
  geom_boxplot()
```



```{r}
listings2 <- listings %>% 
  mutate(dollars_per_room = price / bedrooms,
         dollars_per_accom = price / accommodates)


listings2 %>% 
  group_by(bedrooms) %>% 
  summarize(counter = n(),
            cost = mean(price, na.rm = TRUE),
            dollars_per_room = mean(dollars_per_room, na.rm = TRUE),
            dollars_per_accom = mean(dollars_per_accom, na.rm=TRUE)
  )

listings2 %>% 
  group_by(neighbourhood_cleansed) %>% 
  summarize(count = n(),
            score_avg = mean(review_scores_location, na.rm=TRUE),
            score_var = var(review_scores_location,  na.rm=TRUE))


listings2 %>% 
  group_by(neighbourhood_cleansed) %>% 
  summarize(count = n(),
            score_avg = mean(review_scores_location, na.rm=TRUE),
            score_var = var(review_scores_location,  na.rm=TRUE)) %>% 
  filter(!neighbourhood_cleansed==34 | !neighbourhood_cleansed==19) %>% 
  ggplot(aes(x=score_avg, y=count)) +
  geom_point(aes(size=score_var))

```

```{r}
listings2 %>% 
  group_by(neighbourhood_cleansed) %>% 
  summarize(count = n(),
            price_avg = mean(price, na.rm=TRUE)) %>% 
  arrange(desc(price_avg)) %>% 
  head(10)


listings2 %>% 
  group_by(bedrooms, neighbourhood_cleansed) %>% 
  summarize(price_avg = mean(price, na.rm=TRUE)) %>% 
  filter(bedrooms >= 1 & bedrooms <= 6)
```



```{r}
loc_test <- listings2 %>%
  filter(neighborhood_num %in% c(19, 17, 6, 5, 21)) %>% 
  group_by(bedrooms, neighborhood_num) %>% 
  summarize(count = n(),
            price_avg = round(mean(price, na.rm=TRUE),2),
            price_var = round(var(price, na.rm=TRUE),2)
            )
```



```{r}

super_test <- listings2 %>% 
  group_by(host_is_superhost, neighborhood_num) %>% 
  summarize(price = mean(price, na.rm=TRUE),
            rating_avg = mean(review_scores_rating/20, na.rm=TRUE),
            rating_med = median(review_scores_rating/20, na.rm=TRUE)
  )

listings2

```



```{r}
listings2 %>% 
  ggplot(aes(x=review_scores_rating)) +
  geom_histogram(binwidth=.5)
  scale_x_continuous(limits=c(70,100),
                     )
```




```{r}
listings2 %>% 
  filter(!is.na(review_scores_rating)) %>% 
  ggplot(aes(x=review_scores_rating/20)) +
  geom_histogram(binwidth=.05, color = "black", fill = "#c6d0d9") +
  geom_vline(aes(xintercept=mean(review_scores_rating/20)),
            color="dark blue", linetype="dashed", size=.8) +
  geom_vline(aes(xintercept=median(review_scores_rating/20)),
            color="black", linetype="dashed", size=.8) +
  scale_x_continuous(limits=c(4,5),
                     breaks = seq(4,5, .25)) +
  scale_y_continuous(limits=c(0,1250)) +
  labs(x="Review Score", y="") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        text = element_text(size=18))


# 4660


ratings_only <- data.frame(listings2 %>% filter(!is.na(review_5)) %>% select(review_5))
quantile(ratings_only$review_5, c(.1, .2, .18, .21,.25, .2,.3,.4,.5,.6,.7,.8,.9))
           


listings2 %>% 
  filter(!is.na(review_5) & bedrooms <= 4) %>% 
  group_by(bedrooms) %>% 
  summarize(avg = mean(review_5),
            var = var(review_5),
            med = median(review_5)
            )

```


